# Generated by Django 4.2.4 on 2024-01-12 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "PriceCompare",
            "0002_discprice_price_per_tb_alter_discprice_capacity_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="discprice",
            name="Link",
            field=models.TextField(blank=True, null=True),
        ),
    ]
