# Generated by Django 4.2.4 on 2024-01-12 11:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("PriceCompare", "0003_discprice_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discprice",
            name="price",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
