# Generated by Django 4.2.4 on 2024-01-12 12:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("PriceCompare", "0004_alter_discprice_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="discprice",
            name="price_per_gb",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
