# Generated by Django 4.2.4 on 2023-09-23 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ContentCreation", "0003_blogpost_heading"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="paragraphs",
            field=models.OneToOneField(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blog_posts",
                to="ContentCreation.paragraph",
            ),
        ),
    ]
