# Generated by Django 4.2.4 on 2023-09-23 15:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ContentCreation", "0004_alter_blogpost_paragraphs"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="intro",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.RemoveField(
            model_name="blogpost",
            name="paragraphs",
        ),
        migrations.AddField(
            model_name="blogpost",
            name="paragraphs",
            field=models.ManyToManyField(
                related_name="blog_posts", to="ContentCreation.paragraph"
            ),
        ),
    ]
